version: '1.0'
services:
  database:
    image: 'postgres:15.2'
    ports:
      - "15432:5432"
    environment:
      - 'POSTGRES_DB=librarybooks'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
